### ISSUE TITLE
Failed to save configuration

### ISSUE THREAD

**Issue by ninjazx12r** [bugficks/omramin#1]
[2024-11-26 22:00:37] [E] Failed to save configuration: [Errno 2] No such file or directory: '/home/carlosmoreira/.omramin/config.json'

**Comment by ninjazx12r** [comment]
omramin add

**Comment by bugficks** [comment]
I am unable to reproduce this. 
Tried new user, different VMs with just `omramin add` as well as `omramin add -m 11:22:33:44:55:66 -n test -c bpm` both commands work fine.

**Comment by ninjazx12r** [comment]
Changed PATH_DEFAULT_CONFIG = "~/.omramin/config.json" to PATH_DEFAULT_CONFIG = "config.json" in omramin.py, now it works...

**Comment by bugficks** [comment]
Looks like you cannot write to your home directory for whatever reason. 
Does directory `~/.omramin` exist?
This should make sure it does:
https://github.com/bugficks/omramin/blob/ee9d82c06483516d1b06ff6ce611f420d48db35f/omramin.py#L1073

**Comment by ninjazx12r** [comment]
Solved, thank you!
